name: CI

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
    with:
      run-tests: true

  release:
    name: Release?
    if: github.event_name == 'push' && github.repository == 'unfunco/terraform-aws-oidc-github'
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    uses: unfunco/meta/.github/workflows/release-please.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
