name: CI

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@8a2e3873c609d86b9a67b353a9111bd44171240d # v0.3.0
    with:
      run-tests: true

  release:
    name: Release?
    if: github.event_name == 'push' && github.repository == 'unfunco/terraform-aws-oidc-github'
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    uses: unfunco/meta/.github/workflows/release-please.yaml@8a2e3873c609d86b9a67b353a9111bd44171240d # v0.3.0
