name: CI

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@06f3fca81cc4034ff0cc99c7a7ef58f76ed21077
    with:
      run-tests: true

  release:
    name: Release?
    if: github.event_name == 'push' && github.repository == 'unfunco/terraform-aws-oidc-github'
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    uses: unfunco/meta/.github/workflows/release-please.yaml@06f3fca81cc4034ff0cc99c7a7ef58f76ed21077
