name: PR

on:
  pull_request: { }

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@8a2e3873c609d86b9a67b353a9111bd44171240d # v0.3.0
    with:
      run-tests: true
