name: PR / Label

on:
  pull_request_target: { }

jobs:
  triage:
    name: Triage
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Apply context labels
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        configuration-path: .github/labeler.yaml
        sync-labels: true
    - name: Apply commit message labels
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          const labels = []

          if (context.payload.pull_request.title.startsWith('fix')) {
            labels.push('bug 🐛')
          }

          if (context.payload.pull_request.title.startsWith('chore')) {
            labels.push('chore 🧹')
          }

          if (context.payload.pull_request.title.startsWith('feat')) {
            labels.push('feature 💡')
          }

          if (labels.length > 0) {
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              labels,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          }
